create table passports (
    id int generated by default as identity primary key,
    number varchar(255) not null unique,
    serial varchar(255) not null unique,
    active boolean not null,
    name varchar(255) not null,
    surname varchar(255) not null,
    nationality varchar(255) not null
);

create table airports(
    id int generated by default as identity primary key,
    iata_code varchar(255) not null unique,
    name varchar(255) not null,
    city varchar(255) not null,
    country varchar(255) not null
);

create table air_flights(
    id int generated by default as identity primary key,
    origin_id int references airports (id),
    destination_id int references airports (id),
    price int not null,
    actual boolean not null,
    trip_class smallint not null,
    duration int not null,
    distance int not null,
    departure_date date not null,
    return_date date not null
);

create table tickets(
    id int generated by default as identity primary key,
    full_name_of_passenger varchar(255) not null,
    from_airport_id int references airports (id),
    to_airport_id int references airports (id),
    date_to_issue date not null,
    terminal varchar(255) not null,
    air_flight_id int references air_flights (id)
);

create table persons
(
    id          int generated by default as identity primary key,
    username    varchar(255) not null unique,
    password    varchar(255) not null,
    email       varchar(255) not null unique,
    passport_id int references passports (id),
    ticket_id   int references tickets (id),
    role        smallint     not null,
    active      boolean      not null,
    non_locked  boolean      not null
);
